### ISSUE TITLE
Error "http: multiple response.WriteHeader calls"

### ISSUE THREAD

**Issue by r7vme** [giantswarm/mayu#112]
With latest changes https://github.com/giantswarm/mayu/pull/111 i'm getting following errors 
```
I0819 19:34:27.902511       1 ipxe_handlers.go:249] generating a final stage cloudConfig
I0819 19:34:27.902547       1 cloudconfig.go:38] templates: [./templates/last_stage_cloudconfig.yaml template_snippets/cloudconfig/g8s_master.yaml template_snippets/cloudconfig/g8s_worker.yaml template_snippets/cloudconfig/net_bond.yaml template_snippets/cloudconfig/net_bridge.yaml template_snippets/cloudconfig/net_singlenic.yaml template_snippets/cloudconfig/net_singlevlan.yaml template_snippets/cloudconfig/nfs.yaml template_snippets/cloudconfig/quobyte.yaml template_snippets/cloudconfig/rook.yaml]
mayu: http: multiple response.WriteHeader calls
I0819 19:34:27.904866       1 glog_wrapper.go:18] 172.16.238.28 - - [19/Aug/2017:19:34:27 +0000] "POST /final-cloud-config.yaml HTTP/1.1" 500 8733
I0819 19:34:28.904395       1 ipxe_handlers.go:175] generating a final stage config file
```

**Comment by fgimenez** [comment]
Maybe `template.Execute` is returning an error, is `templates_env.storage` set in mayu.yaml? Anyway, instead of the multiple http header message, the actual template error should be shown, this needs further tweaking

**Comment by fgimenez** [comment]
The `multiple response.WriteHeader calls` you are seeing seems to be related to the fact that, if we don't set a response header before calling any write function, Go will automatically set the response header to 200 with the first of these writes. When the template starts executing in https://github.com/giantswarm/mayu/blob/master/pxemgr/cloudconfig.go#L83 the header is set, and later, when the error is detected in https://github.com/giantswarm/mayu/blob/master/pxemgr/ipxe_handlers.go#L250, the header is set again. A PR is coming to fix this.

But the error looks legit (although the error message doesn't) looks like the template is somehow wrong and the problem wasn't noticed before. I found this issue (template execution errors not being checked) while trying locallab, in my case the template was stopping to being generated after this point https://github.com/giantswarm/hive/blob/master/templates/last_stage_cloudconfig.yaml#L246 because `templates_env.storage` was not defined in mayu.yaml, defining it as an empty string solved the issue in that case and the complete template was properly generated (more about this in giantswarm/hive#105).

I see in that https://github.com/giantswarm/hive/blob/master/templates/last_stage_cloudconfig.yaml also checks for `.ClusterNetwork.NetworkModel` and `.Host.Profile`, not defined entries here might cause template execution errors too. Hope this helps :)
